create table
  public.subscriptions (
    id bigint generated by default as identity,
    created_at timestamp with time zone null default now(),
    token text null,
    platform text null,
    player_id uuid null,
    url text null default 'legacy'::text,
    constraint subscriptions_pkey primary key (id),
    constraint subscriptions_player_id_fkey foreign key (player_id) references players (id)
  ) tablespace pg_default;


  create table
  public.votes (
    id bigint generated by default as identity,
    created_at timestamp with time zone null default now(),
    player_id uuid null,
    week integer null,
    vote_1 integer not null,
    vote_2 integer null,
    vote_3 integer null,
    constraint votes_pkey primary key (id),
    constraint votes_player_id_fkey foreign key (player_id) references players (id)
  ) tablespace pg_default;